name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: make install
      
    - name: Run check
      run: make test
