name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      run: ./configure
      
    - name: Install dependencies
      run: make innstall
      
    - name: Run check
      run: make run
